multitenancy_enabled: false

server:
  http_listen_port: 9009
  log_level: warn

common:
  storage:
    backend: filesystem
    filesystem:
      dir: /data
  ring:
    kvstore:
      store: inmemory

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /data/tsdb
  bucket_store:
    sync_dir: /data/tsdb-sync

compactor:
  data_dir: /data/compactor
  sharding_ring:
    kvstore:
      store: inmemory

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /data/ruler
