/**
 * Create Payment Intent Use Case
 *
 * Command use case: Creates a new payment intent for a completed ride.
 *
 * DESIGN PRINCIPLES:
 * - Idempotent by rideId (returns existing if already created)
 * - Atomic: persist aggregate + enqueue outbox in SAME transaction
 * - Repositories persist aggregates only; outbox enqueue owned by use case
 * - No tenantId (PRD: isolation via ownership/role/geo at inbound boundary)
 */

import type { MoneyCOP } from "../../../../shared/domain/value-objects/money-cop.js";
import type {
  PaymentIntentId,
  RideId,
  RiderId,
} from "../../../../shared/types/ids/index.js";
import { PaymentIntent } from "../../domain/payment-intent.aggregate.js";
import type { FareBreakdownRef } from "../../domain/payment-types.js";
import { mapPaymentDomainEventsToIntegrationEvents } from "../events/payment-event-mapper.js";
import type { ClockPort } from "../ports/clock.port.js";
import type { IdGeneratorPort } from "../ports/id-generator.port.js";
import type { OutboxPort } from "../ports/outbox.port.js";
import type { PaymentRepositoryPort } from "../ports/payment-repository.port.js";
import type { UnitOfWorkPort } from "../ports/unit-of-work.port.js";

/**
 * Input for creating a payment intent
 */
export interface CreatePaymentIntentInput {
  /** Payment intent ID (generated by application boundary) */
  readonly id: PaymentIntentId;
  /** Ride ID this payment is for */
  readonly rideId: RideId;
  /** Rider ID who will be charged */
  readonly riderId: RiderId;
  /** Amount to charge in COP */
  readonly amountCOP: MoneyCOP;
  /** Fare breakdown snapshot */
  readonly fareBreakdown: FareBreakdownRef;
  /** Correlation ID for distributed tracing */
  readonly correlationId: string;
  /** Causation ID (optional) */
  readonly causationId?: string;
}

/**
 * Output from creating a payment intent
 */
export interface CreatePaymentIntentOutput {
  readonly paymentIntentId: PaymentIntentId;
  readonly rideId: RideId;
  readonly riderId: RiderId;
  readonly amountCOP: number;
  readonly currency: "COP";
  readonly createdAtUTC: string;
}

/**
 * Create Payment Intent Use Case
 */
export class CreatePaymentIntentUseCase {
  constructor(
    private readonly uow: UnitOfWorkPort,
    private readonly repo: PaymentRepositoryPort,
    private readonly outbox: OutboxPort,
    private readonly clock: ClockPort,
    private readonly idGen: IdGeneratorPort
  ) {}

  /**
   * Execute: Create payment intent for a ride.
   *
   * Idempotent: Returns existing intent if already created for this ride.
   * Atomic: Persists aggregate + enqueues outbox in same transaction.
   *
   * @param input - Payment intent creation parameters
   * @returns Output with payment intent details
   */
  async execute(
    input: CreatePaymentIntentInput
  ): Promise<CreatePaymentIntentOutput> {
    return this.uow.withTransaction(async (tx) => {
      // Check for existing intent (idempotency by rideId)
      const existing = await this.repo.findByRideId(input.rideId);
      if (existing) {
        // Already exists - return without new events
        return {
          paymentIntentId: existing.id,
          rideId: existing.rideId,
          riderId: existing.riderId,
          amountCOP: existing.amountCOP.amount,
          currency: "COP",
          createdAtUTC: existing.createdAtUTC,
        };
      }

      // Get timestamp for creation
      const createdAtUTC = this.clock.nowUTC();

      // Create aggregate (records PaymentIntentCreated event)
      const intent = PaymentIntent.create({
        id: input.id,
        rideId: input.rideId,
        riderId: input.riderId,
        amountCOP: input.amountCOP,
        fareBreakdown: input.fareBreakdown,
        createdAtUTC,
      });

      // Persist aggregate
      await this.repo.save(intent, tx);

      // Pull domain events from aggregate
      const domainEvents = intent.pullDomainEvents();

      // Map to integration events
      const integrationEvents =
        mapPaymentDomainEventsToIntegrationEvents(domainEvents);

      // Enqueue to outbox atomically
      const envelopes = integrationEvents.map((event) => ({
        id: this.idGen.generate(),
        eventName: event.eventType,
        schemaVersion: event.schemaVersion,
        aggregateType: event.aggregateType,
        aggregateId: event.aggregateId,
        correlationId: event.correlationId,
        causationId: event.causationId,
        occurredAtUTC: event.occurredAtUTC,
        payload: event.payload,
      }));
      await this.outbox.enqueue(envelopes, tx);

      // Return output DTO
      return {
        paymentIntentId: intent.id,
        rideId: intent.rideId,
        riderId: intent.riderId,
        amountCOP: intent.amountCOP.amount,
        currency: "COP",
        createdAtUTC: intent.createdAtUTC,
      };
    });
  }
}
