/**
 * Pure seed data arrays. No I/O — only data definitions.
 *
 * All timestamps are relative to SEED_BASE_DATE for consistency.
 * Locations are realistic Bogota coordinates (Chapinero, Usaquen, Suba zones).
 * Fares in COP (Colombian Pesos).
 */

import {
  SEED_CORRELATION_COMPLETED,
  SEED_CORRELATION_DISPATCHING,
  SEED_DISPATCH_COMPLETED,
  SEED_DISPATCH_DISPATCHING,
  SEED_DRIVER_ANDRES,
  SEED_DRIVER_DIANA,
  SEED_DRIVER_JORGE,
  SEED_DRIVER_SOFIA,
  SEED_FARE_COMPLETED,
  SEED_LOC_ANDRES_1,
  SEED_LOC_ANDRES_2,
  SEED_LOC_ANDRES_3,
  SEED_LOC_DIANA_1,
  SEED_LOC_DIANA_2,
  SEED_LOC_DIANA_3,
  SEED_LOC_SOFIA_1,
  SEED_LOC_SOFIA_2,
  SEED_LOC_SOFIA_3,
  SEED_PAYMENT_COMPLETED,
  SEED_RIDE_CANCELED,
  SEED_RIDE_COMPLETED,
  SEED_RIDE_DISPATCHING,
  SEED_RIDE_EXPIRED,
  SEED_RIDE_STARTED,
  SEED_RIDER_CAMILA,
  SEED_RIDER_JUAN,
  SEED_RIDER_VALENTINA,
  SEED_SETTLEMENT_COMPLETED,
  SEED_TENANT_ID,
  SEED_TRANSITION_ASSIGNED,
  SEED_TRANSITION_CREATED,
  SEED_TRANSITION_DISPATCHING,
  SEED_TRANSITION_STARTED,
} from "./seed-ids.js";

// ── Base date: 2026-02-01 08:00 UTC ────────────────────────────────
const SEED_BASE_DATE = new Date("2026-02-01T08:00:00.000Z");

const minutes = (n: number): Date =>
  new Date(SEED_BASE_DATE.getTime() + n * 60_000);

const iso = (d: Date): string => d.toISOString();

// ── Drivers ─────────────────────────────────────────────────────────
export const SEED_DRIVERS = [
  {
    id: SEED_DRIVER_ANDRES,
    tenant_id: SEED_TENANT_ID,
    state: "AVAILABLE",
    version: 3,
    current_location_latitude: 4.6482,
    current_location_longitude: -74.0628,
    current_location_accuracy_meters: 8.5,
    current_location_bearing_degrees: 45.0,
    current_location_speed_mps: 0.0,
    current_location_recorded_at: iso(minutes(55)),
    registered_at: iso(minutes(-1440)),
    created_at: iso(minutes(-1440)),
    updated_at: iso(minutes(55)),
  },
  {
    id: SEED_DRIVER_SOFIA,
    tenant_id: SEED_TENANT_ID,
    state: "BUSY",
    version: 2,
    current_location_latitude: 4.6951,
    current_location_longitude: -74.0313,
    current_location_accuracy_meters: 12.0,
    current_location_bearing_degrees: 180.0,
    current_location_speed_mps: 8.3,
    current_location_recorded_at: iso(minutes(30)),
    registered_at: iso(minutes(-2880)),
    created_at: iso(minutes(-2880)),
    updated_at: iso(minutes(30)),
  },
  {
    id: SEED_DRIVER_JORGE,
    tenant_id: SEED_TENANT_ID,
    state: "OFFLINE",
    version: 1,
    current_location_latitude: null,
    current_location_longitude: null,
    current_location_accuracy_meters: null,
    current_location_bearing_degrees: null,
    current_location_speed_mps: null,
    current_location_recorded_at: null,
    registered_at: iso(minutes(-4320)),
    created_at: iso(minutes(-4320)),
    updated_at: iso(minutes(-4320)),
  },
  {
    id: SEED_DRIVER_DIANA,
    tenant_id: SEED_TENANT_ID,
    state: "AVAILABLE",
    version: 2,
    current_location_latitude: 4.7336,
    current_location_longitude: -74.0836,
    current_location_accuracy_meters: 6.0,
    current_location_bearing_degrees: 270.0,
    current_location_speed_mps: 0.0,
    current_location_recorded_at: iso(minutes(58)),
    registered_at: iso(minutes(-720)),
    created_at: iso(minutes(-720)),
    updated_at: iso(minutes(58)),
  },
];

// ── Driver Locations (3 per active driver) ──────────────────────────
export const SEED_DRIVER_LOCATIONS = [
  // Andres - Chapinero zone
  {
    id: SEED_LOC_ANDRES_1,
    driver_id: SEED_DRIVER_ANDRES,
    tenant_id: SEED_TENANT_ID,
    latitude: 4.647,
    longitude: -74.062,
    accuracy_meters: 10.0,
    bearing_degrees: 90.0,
    speed_mps: 12.5,
    recorded_at: iso(minutes(50)),
    created_at: iso(minutes(50)),
  },
  {
    id: SEED_LOC_ANDRES_2,
    driver_id: SEED_DRIVER_ANDRES,
    tenant_id: SEED_TENANT_ID,
    latitude: 4.6475,
    longitude: -74.0625,
    accuracy_meters: 9.0,
    bearing_degrees: 60.0,
    speed_mps: 5.0,
    recorded_at: iso(minutes(52)),
    created_at: iso(minutes(52)),
  },
  {
    id: SEED_LOC_ANDRES_3,
    driver_id: SEED_DRIVER_ANDRES,
    tenant_id: SEED_TENANT_ID,
    latitude: 4.6482,
    longitude: -74.0628,
    accuracy_meters: 8.5,
    bearing_degrees: 45.0,
    speed_mps: 0.0,
    recorded_at: iso(minutes(55)),
    created_at: iso(minutes(55)),
  },
  // Sofia - Usaquen zone
  {
    id: SEED_LOC_SOFIA_1,
    driver_id: SEED_DRIVER_SOFIA,
    tenant_id: SEED_TENANT_ID,
    latitude: 4.693,
    longitude: -74.033,
    accuracy_meters: 15.0,
    bearing_degrees: 200.0,
    speed_mps: 10.0,
    recorded_at: iso(minutes(25)),
    created_at: iso(minutes(25)),
  },
  {
    id: SEED_LOC_SOFIA_2,
    driver_id: SEED_DRIVER_SOFIA,
    tenant_id: SEED_TENANT_ID,
    latitude: 4.694,
    longitude: -74.032,
    accuracy_meters: 13.0,
    bearing_degrees: 190.0,
    speed_mps: 9.0,
    recorded_at: iso(minutes(27)),
    created_at: iso(minutes(27)),
  },
  {
    id: SEED_LOC_SOFIA_3,
    driver_id: SEED_DRIVER_SOFIA,
    tenant_id: SEED_TENANT_ID,
    latitude: 4.6951,
    longitude: -74.0313,
    accuracy_meters: 12.0,
    bearing_degrees: 180.0,
    speed_mps: 8.3,
    recorded_at: iso(minutes(30)),
    created_at: iso(minutes(30)),
  },
  // Diana - Suba zone
  {
    id: SEED_LOC_DIANA_1,
    driver_id: SEED_DRIVER_DIANA,
    tenant_id: SEED_TENANT_ID,
    latitude: 4.731,
    longitude: -74.085,
    accuracy_meters: 7.0,
    bearing_degrees: 300.0,
    speed_mps: 6.0,
    recorded_at: iso(minutes(53)),
    created_at: iso(minutes(53)),
  },
  {
    id: SEED_LOC_DIANA_2,
    driver_id: SEED_DRIVER_DIANA,
    tenant_id: SEED_TENANT_ID,
    latitude: 4.732,
    longitude: -74.084,
    accuracy_meters: 6.5,
    bearing_degrees: 280.0,
    speed_mps: 3.0,
    recorded_at: iso(minutes(55)),
    created_at: iso(minutes(55)),
  },
  {
    id: SEED_LOC_DIANA_3,
    driver_id: SEED_DRIVER_DIANA,
    tenant_id: SEED_TENANT_ID,
    latitude: 4.7336,
    longitude: -74.0836,
    accuracy_meters: 6.0,
    bearing_degrees: 270.0,
    speed_mps: 0.0,
    recorded_at: iso(minutes(58)),
    created_at: iso(minutes(58)),
  },
];

// ── Rides ───────────────────────────────────────────────────────────
export const SEED_RIDES = [
  // Completed ride: Chapinero → Zona T (Andres drove Camila)
  {
    id: SEED_RIDE_COMPLETED,
    tenant_id: SEED_TENANT_ID,
    rider_id: SEED_RIDER_CAMILA,
    driver_id: SEED_DRIVER_ANDRES,
    state: "COMPLETED",
    version: 5,
    pickup_lat: 4.64,
    pickup_lng: -74.063,
    dropoff_lat: 4.666,
    dropoff_lng: -74.053,
    requested_at: iso(minutes(0)),
    started_at: iso(minutes(10)),
    completed_at: iso(minutes(40)),
    expires_at: null,
    created_at: iso(minutes(0)),
    updated_at: iso(minutes(40)),
  },
  // In-progress ride: Usaquen → Parque 93 (Sofia driving Juan)
  {
    id: SEED_RIDE_STARTED,
    tenant_id: SEED_TENANT_ID,
    rider_id: SEED_RIDER_JUAN,
    driver_id: SEED_DRIVER_SOFIA,
    state: "STARTED",
    version: 4,
    pickup_lat: 4.695,
    pickup_lng: -74.032,
    dropoff_lat: 4.676,
    dropoff_lng: -74.048,
    requested_at: iso(minutes(15)),
    started_at: iso(minutes(25)),
    completed_at: null,
    expires_at: null,
    created_at: iso(minutes(15)),
    updated_at: iso(minutes(25)),
  },
  // Dispatching ride: Suba → Centro (no driver yet)
  {
    id: SEED_RIDE_DISPATCHING,
    tenant_id: SEED_TENANT_ID,
    rider_id: SEED_RIDER_VALENTINA,
    driver_id: null,
    state: "DISPATCHING",
    version: 2,
    pickup_lat: 4.734,
    pickup_lng: -74.083,
    dropoff_lat: 4.5981,
    dropoff_lng: -74.0758,
    requested_at: iso(minutes(58)),
    started_at: null,
    completed_at: null,
    expires_at: iso(minutes(73)),
    created_at: iso(minutes(58)),
    updated_at: iso(minutes(59)),
  },
  // Canceled ride: rider canceled before assignment
  {
    id: SEED_RIDE_CANCELED,
    tenant_id: SEED_TENANT_ID,
    rider_id: SEED_RIDER_CAMILA,
    driver_id: null,
    state: "CANCELED",
    version: 3,
    pickup_lat: 4.651,
    pickup_lng: -74.059,
    dropoff_lat: 4.62,
    dropoff_lng: -74.07,
    requested_at: iso(minutes(-120)),
    started_at: null,
    completed_at: null,
    expires_at: null,
    created_at: iso(minutes(-120)),
    updated_at: iso(minutes(-115)),
  },
  // Expired ride: no driver found in time
  {
    id: SEED_RIDE_EXPIRED,
    tenant_id: SEED_TENANT_ID,
    rider_id: SEED_RIDER_JUAN,
    driver_id: null,
    state: "EXPIRED",
    version: 3,
    pickup_lat: 4.71,
    pickup_lng: -74.072,
    dropoff_lat: 4.68,
    dropoff_lng: -74.045,
    requested_at: iso(minutes(-180)),
    started_at: null,
    completed_at: null,
    expires_at: iso(minutes(-165)),
    created_at: iso(minutes(-180)),
    updated_at: iso(minutes(-165)),
  },
];

// ── Ride Transitions (full audit trail for the completed ride) ──────
export const SEED_RIDE_TRANSITIONS = [
  {
    id: SEED_TRANSITION_CREATED,
    ride_id: SEED_RIDE_COMPLETED,
    from_state: "CREATED",
    to_state: "DISPATCHING",
    changed_by: "system",
    changed_by_role: "system",
    reason: "Ride requested, dispatching started",
    correlation_id: SEED_CORRELATION_COMPLETED,
    created_at: iso(minutes(0)),
  },
  {
    id: SEED_TRANSITION_DISPATCHING,
    ride_id: SEED_RIDE_COMPLETED,
    from_state: "DISPATCHING",
    to_state: "ASSIGNED",
    changed_by: "system",
    changed_by_role: "system",
    reason: "Driver assigned by dispatch",
    correlation_id: SEED_CORRELATION_COMPLETED,
    created_at: iso(minutes(3)),
  },
  {
    id: SEED_TRANSITION_ASSIGNED,
    ride_id: SEED_RIDE_COMPLETED,
    from_state: "ASSIGNED",
    to_state: "STARTED",
    changed_by: SEED_DRIVER_ANDRES,
    changed_by_role: "driver",
    reason: "Driver started ride",
    correlation_id: SEED_CORRELATION_COMPLETED,
    created_at: iso(minutes(10)),
  },
  {
    id: SEED_TRANSITION_STARTED,
    ride_id: SEED_RIDE_COMPLETED,
    from_state: "STARTED",
    to_state: "COMPLETED",
    changed_by: SEED_DRIVER_ANDRES,
    changed_by_role: "driver",
    reason: "Ride completed at destination",
    correlation_id: SEED_CORRELATION_COMPLETED,
    created_at: iso(minutes(40)),
  },
];

// ── Fare Calculation (completed ride) ───────────────────────────────
export const SEED_FARE_CALCULATIONS = [
  {
    id: SEED_FARE_COMPLETED,
    ride_id: SEED_RIDE_COMPLETED,
    tenant_id: SEED_TENANT_ID,
    base_fare_cop: 4500,
    distance_km: 3.2,
    duration_minutes: 30.0,
    distance_component_cop: 6400,
    time_component_cop: 7100,
    total_fare_cop: 18_000,
    minimum_applied: false,
    pricing_version: "2026-01-01",
    calculated_at: iso(minutes(40)),
    created_at: iso(minutes(40)),
    updated_at: iso(minutes(40)),
  },
];

// ── Payment Intent (completed ride) ─────────────────────────────────
export const SEED_PAYMENT_INTENTS = [
  {
    id: SEED_PAYMENT_COMPLETED,
    tenant_id: SEED_TENANT_ID,
    ride_id: SEED_RIDE_COMPLETED,
    rider_id: SEED_RIDER_CAMILA,
    amount_cop: 18_000,
    currency: "COP",
    fare_base: 4500,
    fare_distance_component: 6400,
    fare_time_component: 7100,
    fare_minimum_applied: false,
    created_at_utc: iso(minutes(41)),
    created_at: iso(minutes(41)),
    updated_at: iso(minutes(41)),
  },
];

// ── Settlement Attempt (succeeded) ──────────────────────────────────
export const SEED_SETTLEMENT_ATTEMPTS = [
  {
    id: SEED_SETTLEMENT_COMPLETED,
    payment_intent_id: SEED_PAYMENT_COMPLETED,
    tenant_id: SEED_TENANT_ID,
    attempt_number: 1,
    idempotency_key: "seed_idem_settlement_001",
    outcome: "SUCCEEDED",
    provider_ref: "seed_psp_ref_001",
    reason_code: null,
    initiated_at_utc: iso(minutes(41)),
    completed_at_utc: iso(minutes(42)),
    created_at: iso(minutes(41)),
    updated_at: iso(minutes(42)),
  },
];

// ── Dispatch Audits ─────────────────────────────────────────────────
export const SEED_DISPATCH_AUDITS = [
  // Successful dispatch for completed ride
  {
    id: SEED_DISPATCH_COMPLETED,
    tenant_id: SEED_TENANT_ID,
    correlation_id: SEED_CORRELATION_COMPLETED,
    ride_id: SEED_RIDE_COMPLETED,
    selected_driver_id: SEED_DRIVER_ANDRES,
    candidates_json: JSON.stringify([
      { driverId: SEED_DRIVER_ANDRES, distanceMeters: 450 },
      { driverId: SEED_DRIVER_DIANA, distanceMeters: 2100 },
    ]),
    candidates_count: 2,
    selection_criteria: "nearest_available",
    search_radius_meters: 3000,
    search_center_latitude: 4.64,
    search_center_longitude: -74.063,
    outcome: "SUCCEEDED",
    failure_code: null,
    dispatched_at: iso(minutes(2)),
    created_at: iso(minutes(2)),
  },
  // Dispatching ride - still searching
  {
    id: SEED_DISPATCH_DISPATCHING,
    tenant_id: SEED_TENANT_ID,
    correlation_id: SEED_CORRELATION_DISPATCHING,
    ride_id: SEED_RIDE_DISPATCHING,
    selected_driver_id: null,
    candidates_json: JSON.stringify([]),
    candidates_count: 0,
    selection_criteria: "nearest_available",
    search_radius_meters: 3000,
    search_center_latitude: 4.734,
    search_center_longitude: -74.083,
    outcome: "NO_ELIGIBLE",
    failure_code: null,
    dispatched_at: iso(minutes(59)),
    created_at: iso(minutes(59)),
  },
];
