services:
  otel-collector:
    ports:
      - "127.0.0.1:4317:4317"
      - "127.0.0.1:4318:4318"
      - "127.0.0.1:13133:13133"
      - "127.0.0.1:8889:8889"
      - "127.0.0.1:55679:55679"

  prometheus:
    ports:
      - "127.0.0.1:9090:9090"

  mimir:
    ports:
      - "127.0.0.1:9009:9009"

  grafana:
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: ${GRAFANA_ANON_ENABLED:-true}
      GF_AUTH_ANONYMOUS_ORG_ROLE: ${GRAFANA_ANON_ROLE:-Admin}
